// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmFygb-ZPFTBbvNxjAEpJ6qdvBicaM0rk',
    appId: '1:615624498370:web:9884f29f61df3de703af5b',
    messagingSenderId: '615624498370',
    projectId: 'push-notification-d7369',
    authDomain: 'push-notification-d7369.firebaseapp.com',
    storageBucket: 'push-notification-d7369.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyo0L60_X711cF3esGcK8WWSYR9IFpauM',
    appId: '1:615624498370:android:2c4cba8d7f9c0a0403af5b',
    messagingSenderId: '615624498370',
    projectId: 'push-notification-d7369',
    storageBucket: 'push-notification-d7369.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr5gSJAD4Q7CzgS4SZVHl7w5K1RVLA6rw',
    appId: '1:615624498370:ios:fbf72004ca9bba7c03af5b',
    messagingSenderId: '615624498370',
    projectId: 'push-notification-d7369',
    storageBucket: 'push-notification-d7369.appspot.com',
    iosBundleId: 'com.example.pillReminderSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr5gSJAD4Q7CzgS4SZVHl7w5K1RVLA6rw',
    appId: '1:615624498370:ios:fbf72004ca9bba7c03af5b',
    messagingSenderId: '615624498370',
    projectId: 'push-notification-d7369',
    storageBucket: 'push-notification-d7369.appspot.com',
    iosBundleId: 'com.example.pillReminderSystem',
  );
}
